"""Update settings model

Revision ID: 975d38bed1d7
Revises: 99ace67d2145
Create Date: 2025-04-02 22:49:45.957187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975d38bed1d7'
down_revision = '99ace67d2145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('settings', sa.Column('type', sa.String(length=20), nullable=True))
    op.drop_column('settings', 'label')
    op.drop_column('settings', 'setting_id')
    op.drop_column('settings', 'data_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('data_type', sa.VARCHAR(length=20), nullable=True))
    op.add_column('settings', sa.Column('setting_id', sa.INTEGER(), nullable=False))
    op.add_column('settings', sa.Column('label', sa.VARCHAR(length=100), nullable=False))
    op.drop_column('settings', 'type')
    op.drop_column('settings', 'id')
    # ### end Alembic commands ###
